services:
  - cluster
  - session
  - storage
  - meta
  - task
  - web
cluster:
  backend: fixed
  node_timeout: 120
  node_check_interval: 1
  ray:
    supervisor_exclusive_node: no
storage:
  backends: [ray]
meta:
  store: dict
task:
  default_config:
    optimize_tileable_graph: yes
    optimize_chunk_graph: yes
    fuse_enabled: yes
